### ISSUE TITLE
Does Flexor work with client side blazor?

### ISSUE THREAD

**Issue by americanslon** [DerekChasse/Flexor#19]
I can't get sizes to work and in my quest to figure out why, I noticed that I don't have the `flexor_dynamic_css` component in my index.html. Even if I put one in myself flexor doesn't populate it with anything. I also noticed that you use serverside in the demo project. 

So hence the question, is this supposed to work with clientside blazor?

**Comment by americanslon** [comment]
For client side Blazor you need to add

`    <script src="_content/Flexor/flexor.js"></script>`
`    <link href="_content/Flexor/flexor.css" rel="stylesheet">  `

to your index.html.

I originally added the `css` but didn't know about `js`, thought I was going insane...

May I suggest a more thorough install instructions...:)

**Comment by DerekChasse** [comment]
Thanks for trying out the library.  I hope it's working out for you.

Flexor's sample site was initially done with client-side, but I switched to have it be done using the server side template when .Net 3.0 went GA, and Blazor client-side support was delayed to a later release.

Microsoft had your script and link blocks documented and I left it to them to provide the official word on "how to reference an RCL in client-side Blazor".

You're point is valid though and I'll work on enhancing the documentation.

**Comment by americanslon** [comment]
With how new blazor is info is scattered - I think it'd be beneficial to see as much info in as many places.

Really awesome job, the library is more than working for me!
